del /S /Q *.groupproj.local
del /S /Q *.dproj.local
del /S /Q *.sublime-workspace
del /S /Q *.identcache
del /S /Q *.dcu
del /S /Q *.ddp
del /S /Q *.cfg
del /S /Q *.rsm
del /S /Q *.stat
del /S /Q *.o
del /S /Q *.cvsignore
del /S /Q Thumbs.db
del /S/AH /Q Thumbs.db
del /S /Q *.~*
